services:
  cs:
    build: .
    restart: always
    ports:
      - 27016:27016/udp
      - 27016:27016/tcp
    environment:
      - PORT=27016
      - MAP=fy_pool_day
      - MAXPLAYERS=16
      - SV_LAN=0

    volumes:
      # Native configs
      - ./configs/server.cfg:/home/steam/cstrike/cstrike/server.cfg
      - ./configs/mapcycle.txt:/home/steam/cstrike/cstrike/mapcycle.txt

      # Mod configs
      - ./configs/plugins.ini:/home/steam/cstrike/cstrike/addons/amxmodx/configs/plugins.ini
      - ./configs/users.ini:/home/steam/cstrike/cstrike/addons/amxmodx/configs/users.ini
      - ./configs/podbot.cfg:/home/steam/cstrike/cstrike/addons/podbot/podbot.cfg

      # Gamemode configs
      - ./configs/gungame.cfg:/home/steam/cstrike/cstrike/addons/amxmodx/configs/gungame.cfg
