services:
  abiotic:
    image: ghcr.io/pleut/abiotic-factor-linux-docker:latest
    restart: unless-stopped
    ports:
      - "0.0.0.0:7777:7777/udp"
      - "0.0.0.0:27015:27015/udp"
    environment:
      # Setup
      - Port=7777
      - QueryPort=27015
      - UsePerfThreads=true
      - NoAsyncLoadingThread=true
      - AutoUpdate=true
      # Server
      - SteamServerName=nabos
      - WorldSaveName=nabos
      - MaxServerPlayers=6
      - ServerPassword=maduro
      # Game
      - AdditionalArgs=-SandboxIniPath=Config/WindowsServer/sandbox.ini
    volumes:
      - ./server:/server
      - ./data:/server/AbioticFactor/Saved
      - ./sandbox.ini:/Config/WindowsServer/sandbox.ini
